apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simplelocation-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: simplelocation
    spec:
      containers:
      - name: svcp-simplelocation
        image: gcr.io/svcp-simplelocation/simplelocation
        ports:
        - containerPort: 3000
